### ISSUE TITLE
lineplot

### ISSUE THREAD

**Issue by martin-raden** [MatthiasHerrmann/Long_Range_RNA_Interactions#1]
- [x] wie gesagt wärs gut, wenn du die ausrichtung nicht bzgl. genomstart/-end machst, sondern bzgl. CDS start/end. sprich in beiden plots wär die position 1 (oder 0) der übergang zwischen cds und utr. die positionen kannst du dir aus seqlength und cdsextensionlength ausrechnen und entsprechend (pro sequenze) die indizes verschieben

um das verschieben obsolete zu machen, hatte ich vorgeschlagen, dass du schon im intarna call die "idxpos0" positions entsprechend setzt, dann sind ist interaction position information nämlich schon bzgl. selbiger.. aber kann auch als postprocessing fürs visualisieren reingepackt werden

- [x] ich würd die gruppen im lineplot gern sehen.. dazu ggf. die CDS (oder den UTR) entsprechend einfärben und eine farblegende neben den plot packen.

- [x] der lineplot würde sich mächtig gut eignen auch alternative interaktionsstellen zu visualisieren.

- dazu müsste man intarna am besten 2mal aufrufen, um non-overlapping interactions in der einen oder der anderen sequenz zu erlauben/verbieten
 * --outOverlap=T -n 3
 * --outOverlap=Q -n 3
- die ergebnisse könnte man dann entsprechend noch eintragen, ggf. mit colorscale basierend auf der entsprechenden energie

damit könnte man dann sehen, ob ggf. second best interactions in die konservierten locations passen...

**Comment by martin-raden** [comment]
ping @MatthiasHerrmann @mtw

**Comment by martin-raden** [comment]
- [ ] im lineplot kann die CDS region jeweils um 100 gekürzt werden, weil wir dort ja keine prediction zulassen. geht am einfachsten über eine entsprechende x-achsen beschränkung des plots. dann kannst du die originalkoordinaten nehmen.

**Comment by RNAforecast** [comment]
der lineplot sieht gut aus! wie von @martin-raden erwähnt wäre es schön, ein klassifizierung im lineplot zu sehen. am besten würde sich hier die ecologic group (in deiner parameter_table wäre das die Spalte "type") eignen.
wir kennen für jede dieser sequenzen die konservierten RNA strukturelemente, bzw können wir die genaue position innerhalb der 3 bzw 5utr  mit hilfe von covarianzmodellen leicht bestimmen. in der literatur wird manchmal erwähnt dass die cyclisation sequenzen oft benachbart zu bestimmten RNA strukturelementen gefunden wurden (zumindest bei den paar beispielen die genauer analysiert wurden). in weiterer folge wäre es daher auch gut, diese als farblich gekennzeichnete blöcke in den lineplot mit aufzunehmen. lass und das im nächsten call genauer besprechen.

**Comment by martin-raden** [comment]
> der lineplot sieht gut aus! wie von @martin-raden erwähnt wäre es schön, ein klassifizierung im lineplot zu sehen. am besten würde sich hier die ecologic group (in deiner parameter_table wäre das die Spalte "type") eignen. wir kennen für jede dieser sequenzen die konservierten RNA strukturelemente, bzw können wir die genaue position innerhalb der 3 bzw 5utr mit hilfe von covarianzmodellen leicht bestimmen. in der literatur wird manchmal erwähnt dass die cyclisation sequenzen oft benachbart zu bestimmten RNA strukturelementen gefunden wurden (zumindest bei den paar beispielen die genauer analysiert wurden). in weiterer folge wäre es daher auch gut, diese als farblich gekennzeichnete blöcke in den lineplot mit aufzunehmen. lass und das im nächsten call genauer besprechen.

siehe https://www.biorxiv.org/content/10.1101/2022.08.18.504478v2.full.pdf seite 43, da sind so elemente farblich markiert

**Comment by martin-raden** [comment]
frage: sind interactions im 5'UTR korreliert mit stemloopA auflösung, siehe https://michaelwolfinger.com/files/papers/Harima-2021.pdf figure 5a

**Comment by martin-raden** [comment]
hab gerade den neuen lineplot angeschaut: sehr schick! scheinbar liegen die 3'UTR interactions häufig in relativ gleichem abstand zum genomende..

- [ ] könntest du ggf. einen dritten lineplot noch drunter setzen, der bzgl genomende "aligniert ist"? dazu müsstest du von alle koordinaten einfach die UTR länge abziehen, dann sollte das genomende die 0 haben und alle annotations entsprechend verschoben werden...

Danke!

**Comment by martin-raden** [comment]
> hab gerade den neuen lineplot angeschaut: sehr schick! scheinbar liegen die 3'UTR interactions häufig in relativ gleichem abstand zum genomende..
> 
>     * [ ]  könntest du ggf. einen dritten lineplot noch drunter setzen, der bzgl genomende "aligniert ist"? dazu müsstest du von alle koordinaten einfach die UTR länge abziehen, dann sollte das genomende die 0 haben und alle annotations entsprechend verschoben werden...
> 
> 
> Danke!

update: keinen dritten plot machen, sondern den 3'UTR plot bzgl genomende anpassen und gut... Danke!

**Comment by MatthiasHerrmann** [comment]
Ich habe es jetzt vorerst als 3. Plot gemacht. Ich meine, das ist sogar genau das, was ich am Anfang hatte oder? Zumindest für das 3' Ende

**Comment by martin-raden** [comment]
> Ich habe es jetzt vorerst als 3. Plot gemacht. Ich meine, das ist sogar genau das, was ich am Anfang hatte oder? Zumindest für das 3' Ende

passt, super so! Danke!
