### ISSUE TITLE
noch lokaleres falten für acc-berechnung

### ISSUE THREAD

**Issue by martin-raden** [MatthiasHerrmann/Long_Range_RNA_Interactions#2]
Hi @MatthiasHerrmann 

mach bitte noch einen subbranch von `seedbp5` auf (zb `seedbp5-acc50`), in welchem du die accessibility berechnung auf ein 50er window (statt bisher 100) einschränkst.

dafür dann bitte auch den lineplot.

danke,
Martin

**Comment by MatthiasHerrmann** [comment]
Habe ich hinzugefügt!

**Comment by martin-raden** [comment]
danke!
